package controller;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import tools.CertDAO;
import tools.User;

@WebServlet(name = "ReportServlet", urlPatterns = {"/generateReport"})
public class ReportServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        
        // 1. Session & Role Validation
        HttpSession session = request.getSession(false);
        User currentUser = (session != null) ? (User) session.getAttribute("currentUser") : null;
        
        if (currentUser == null || !currentUser.getRole().equalsIgnoreCase("admin")) {
            response.sendRedirect("login");
            return;
        }

        // 2. Fetch Dates from JSP Form
        String startDate = request.getParameter("startDate");
        String endDate = request.getParameter("endDate");

        // 3. Setup PDF Response
        LocalDateTime now = LocalDateTime.now();
        String timestamp = now.format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));
        String filename = "Performance_Audit_" + timestamp + ".pdf";

        response.setContentType("application/pdf");
        response.setHeader("Content-Disposition", "attachment; filename=\"" + filename + "\"");

        try {
            // 4. Initialize iText Document
            Document document = new Document(PageSize.A4);
            PdfWriter.getInstance(document, response.getOutputStream());
            document.open();
            
            // Fonts
            Font titleFont = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
            Font headerFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD, BaseColor.WHITE);
            Font normalFont = new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL);
            
            // Document Header
            document.add(new Paragraph("EduPortal System - Performance Audit", titleFont));
            document.add(new Paragraph("Report Timeframe: " + startDate + " to " + endDate));
            document.add(new Paragraph("Generated by Admin: " + currentUser.getUsername()));
            document.add(new Paragraph("Generated on: " + now.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))));
            document.add(new Paragraph(" ")); // Spacer
            
            // 5. Create Table
            PdfPTable table = new PdfPTable(4); // 4 columns
            table.setWidthPercentage(100);
            
            // Table Headers
            String[] headers = {"Student Username", "Course Code", "Score (%)", "Timestamp"};
            for (String header : headers) {
                PdfPCell cell = new PdfPCell(new Phrase(header, headerFont));
                cell.setBackgroundColor(new BaseColor(139, 92, 246)); // Purple theme matching UI
                cell.setPadding(8);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(cell);
            }

            // 6. Fetch Data and Populate Table
            CertDAO certDAO = new CertDAO();
            List<Map<String, String>> auditLogs = certDAO.getCertificationsByDate(getServletContext(), startDate, endDate); 
            
            if (auditLogs.isEmpty()) {
                PdfPCell emptyCell = new PdfPCell(new Phrase("No exams completed in this timeframe.", normalFont));
                emptyCell.setColspan(4);
                emptyCell.setHorizontalAlignment(Element.ALIGN_CENTER);
                emptyCell.setPadding(10);
                table.addCell(emptyCell);
            } else {
                for (Map<String, String> log : auditLogs) {
                    table.addCell(new Phrase(log.get("uname"), normalFont));
                    table.addCell(new Phrase(log.get("course_code"), normalFont));
                    table.addCell(new Phrase(log.get("score") + "%", normalFont));
                    table.addCell(new Phrase(log.get("issue_date"), normalFont));
                }
            }

            document.add(table);
            document.close();
            
        } catch (Exception e) {
            e.printStackTrace();
            request.setAttribute("errorMessage", "Error generating the Audit PDF.");
            request.getRequestDispatcher("/general_error.jsp").forward(request, response);
        }
    }
}